version: "3.7"

services:
    mysql-development:
        image: mysql:5.7.27
        container_name: redesigned-db
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: database_development
        ports:
            - "3306:3306"
    admin:
        image: adminer
        container_name: admin-db
        ports:
            - "8080:8080"
volumes:
    mysql-data:
