version: 2
jobs:
  deploy-stage:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Stage to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGE.git master
  deploy-production:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Production to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PRODUCTION.git master

workflows:
  version: 2
  deploy-stage:
    jobs:
      - deploy-stage:
          filters:
            branches:
              only: stage
  deploy-production:
    jobs:
      - deploy-production:
          filters:
            branches:
              only: master